import { Component, ElementRef, viewChild } from '@angular/core';
import { RouterLink } from '@angular/router';

export type NewsKind = 'nota' | 'programa' | 'informe' | 'normativa' | 'recurso';

export interface NewsItem {
  id: string;
  kind: NewsKind;
  year: number;
  date: string;
  tag: string;
  source: string;
  title: string;
  excerpt: string;
  url: string;
  linkLabel: string;
  image: string;
  imageAlt: string;
  featured?: boolean;
}

@Component({
  selector: 'app-novedades',
  imports: [RouterLink],
  templateUrl: './novedades.component.html',
  styleUrl: './novedades.component.css',
})
export class NovedadesComponent {
  readonly catalogUpdated = 'agosto 2026';
  readonly kinds: { id: 'todas' | NewsKind; label: string }[] = [
    { id: 'todas', label: 'Todas' },
    { id: 'recurso', label: 'Recursos' },
    { id: 'programa', label: 'Programas' },
    { id: 'informe', label: 'Informes' },
    { id: 'nota', label: 'Notas' },
    { id: 'normativa', label: 'Normativa' },
  ];

  selectedKind: 'todas' | NewsKind = 'todas';
  selectedYear: number | 'todos' | 'anteriores' = 'todos';
  readonly recentYears = [2026, 2025, 2024, 2023, 2022, 2021, 2020];

  private readonly carousel = viewChild<ElementRef<HTMLElement>>('newsCarousel');

  news: NewsItem[] = [
    {
      id: 'ovd-2026-anual',
      kind: 'nota',
      year: 2026,
      date: '2026-04-28',
      tag: 'Justicia',
      source: 'Corte Suprema de Justicia',
      title: 'La OVD realizó 18.014 atenciones en 2025',
      excerpt:
        'Informe anual publicado en abril de 2026: 10.124 presentaciones y 7.890 consultas, un 5% más que el año anterior.',
      url: 'https://www.ovd.gov.ar/ovd/novedades/detalle/13182',
      linkLabel: 'Leer nota',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
      featured: true,
    },
    {
      id: 'ovd-2026-trimestre',
      kind: 'informe',
      year: 2026,
      date: '2026-03-20',
      tag: 'OVD',
      source: 'Oficina de Violencia Doméstica',
      title: 'Informe estadístico: 4° trimestre de 2025',
      excerpt:
        'Publicado en marzo de 2026. La OVD atendió 2.731 presentaciones en ese trimestre, en su mayoría fuera del horario judicial.',
      url: 'https://ovd.gov.ar/ovd/novedades/detalle/12764',
      linkLabel: 'Leer informe',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
      featured: true,
    },
    {
      id: 'ovd-estadisticas',
      kind: 'recurso',
      year: 2026,
      date: '2026-03-20',
      tag: 'OVD',
      source: 'Corte Suprema de Justicia',
      title: 'Estadísticas de la OVD',
      excerpt:
        'Informes trimestrales y anuales sobre violencia doméstica, para consultar o descargar desde el sitio de la Corte.',
      url: 'https://www.ovd.gob.ar/ovd/estadisticas',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
      featured: true,
    },
    {
      id: 'linea-144',
      kind: 'recurso',
      year: 2026,
      date: '2026-01-15',
      tag: 'Nación',
      source: 'Ministerio de Justicia',
      title: 'Línea 144',
      excerpt:
        'Atención, contención y asesoramiento las 24 horas ante violencia por motivos de género. Gratuita y confidencial.',
      url: 'https://www.argentina.gob.ar/linea-144',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-helpline.jpg',
      imageAlt: 'Persona sosteniendo un teléfono para pedir ayuda',
      featured: true,
    },
    {
      id: 'ovd-nnya-2026',
      kind: 'informe',
      year: 2026,
      date: '2026-06-19',
      tag: 'OVD',
      source: 'Oficina de Violencia Doméstica',
      title: '3.924 niñas, niños y adolescentes afectados en 2025',
      excerpt:
        'Informe de junio de 2026: fueron el 31% de los casos de la OVD. En el 32% se identificó riesgo alto o altísimo.',
      url: 'https://www.ovd.gov.ar/ovd/novedades/detalle/13823',
      linkLabel: 'Leer informe',
      image: '/assets/news/news-support.jpg',
      imageAlt: 'Dos personas acompañándose al aire libre',
      featured: true,
    },
    {
      id: 'ovd-encuesta-2026',
      kind: 'informe',
      year: 2026,
      date: '2026-02-23',
      tag: 'OVD',
      source: 'Oficina de Violencia Doméstica',
      title: 'Encuesta de calidad de atención 2025',
      excerpt:
        'Publicada en febrero de 2026. El 84% calificó la atención con el máximo puntaje y el 93% se sintió escuchada.',
      url: 'https://www.ovd.gob.ar/ovd/novedades/detalle/12442',
      linkLabel: 'Leer resultados',
      image: '/assets/news/news-helpline.jpg',
      imageAlt: 'Persona sosteniendo un teléfono para pedir ayuda',
    },
    {
      id: 'ovd-enero-2026',
      kind: 'nota',
      year: 2026,
      date: '2026-02-04',
      tag: 'OVD',
      source: 'Oficina de Violencia Doméstica',
      title: 'Más de 1.150 personas afectadas en enero',
      excerpt:
        'En el primer mes de 2026 la OVD recibió a 1.721 personas en CABA. En el 14% de los casos hubo amenazas de muerte.',
      url: 'https://www.ovd.gov.ar/ovd/novedades/detalle/12262',
      linkLabel: 'Leer nota',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'linea-144-pba',
      kind: 'recurso',
      year: 2025,
      date: '2025-02-15',
      tag: 'PBA',
      source: 'Ministerio de Mujeres y Diversidad',
      title: 'Línea 144 en la Provincia',
      excerpt:
        'Las llamadas desde Buenos Aires se atienden en la sede provincial. También hay WhatsApp, Telegram y email.',
      url: 'https://www.gba.gob.ar/mujeres/linea144',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-helpline.jpg',
      imageAlt: 'Persona sosteniendo un teléfono para pedir ayuda',
    },
    {
      id: 'ovd',
      kind: 'recurso',
      year: 2025,
      date: '2025-09-01',
      tag: 'Justicia',
      source: 'Corte Suprema de Justicia',
      title: 'Oficina de Violencia Doméstica',
      excerpt:
        'Recibe denuncias las 24 horas en Lavalle 1250, CABA. También toma denuncias de trata con explotación sexual en todo el país.',
      url: 'https://ovd.gob.ar/ovd/',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
      featured: true,
    },
    {
      id: 'proteccion-violencia',
      kind: 'recurso',
      year: 2025,
      date: '2025-01-20',
      tag: 'Nación',
      source: 'Ministerio de Justicia',
      title: 'Protección contra toda forma de violencia',
      excerpt:
        'Información oficial sobre tipos de violencia, derechos y cómo pedir ayuda desde el Estado nacional.',
      url: 'https://www.argentina.gob.ar/justicia/proteccion-contra-toda-forma-de-violencia',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-support.jpg',
      imageAlt: 'Dos personas acompañándose al aire libre',
    },
    {
      id: 'mujeres-pba',
      kind: 'programa',
      year: 2025,
      date: '2025-01-10',
      tag: 'PBA',
      source: 'Gobierno de la Provincia de Buenos Aires',
      title: 'Ministerio de Mujeres y Diversidad',
      excerpt:
        'Políticas provinciales de igualdad, prevención de violencias y recursos territoriales.',
      url: 'https://www.gba.gob.ar/mujeres',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-community.jpg',
      imageAlt: 'Encuentro comunitario al aire libre',
    },
    {
      id: 'inadi-decreto',
      kind: 'normativa',
      year: 2024,
      date: '2024-08-06',
      tag: 'Nación',
      source: 'Boletín Oficial',
      title: 'Disolución del INADI',
      excerpt:
        'El decreto 696/2024 disolvió el instituto. Las políticas contra la discriminación quedaron a cargo del Ministerio de Justicia.',
      url: 'https://www.argentina.gob.ar/normativa/nacional/decreto-696-2024-402470/texto',
      linkLabel: 'Leer decreto',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'acompanar-2024',
      kind: 'normativa',
      year: 2024,
      date: '2024-08-23',
      tag: 'Nación',
      source: 'InfoLEG',
      title: 'Modificación del Programa Acompañar',
      excerpt:
        'El decreto 755/2024 cambió plazos y requisitos del apoyo económico para personas en riesgo por violencia de género.',
      url: 'https://servicios.infoleg.gob.ar/infolegInternet/anexos/400000-404999/403276/norma.htm',
      linkLabel: 'Leer norma',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'inadi-decreto-resumen',
      kind: 'nota',
      year: 2024,
      date: '2024-08-06',
      tag: 'Nación',
      source: 'InfoLEG',
      title: 'Resumen del decreto 696/2024',
      excerpt:
        'Ficha oficial de la norma que disolvió el INADI y transfirió recursos al Ministerio de Justicia.',
      url: 'https://www.argentina.gob.ar/normativa/nacional/decreto-696-2024-402470',
      linkLabel: 'Ver ficha',
      image: '/assets/news/news-equality.jpg',
      imageAlt: 'Personas caminando juntas por la ciudad',
    },
    {
      id: 'acompanar-ficha-2024',
      kind: 'normativa',
      year: 2024,
      date: '2024-08-23',
      tag: 'Nación',
      source: 'InfoLEG',
      title: 'Ficha del decreto 755/2024',
      excerpt:
        'Resumen oficial de la norma que modificó plazos y requisitos del Programa Acompañar.',
      url: 'https://www.argentina.gob.ar/normativa/nacional/decreto-755-2024-403276',
      linkLabel: 'Ver ficha',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'acompanar-programa',
      kind: 'programa',
      year: 2024,
      date: '2024-08-20',
      tag: 'Nación',
      source: 'Ministerio de Justicia',
      title: 'Programa Acompañar',
      excerpt:
        'Apoyo económico y acompañamiento para personas en riesgo por violencia de género. La normativa vigente se actualizó en 2024.',
      url: 'https://www.argentina.gob.ar/generos/plan_nacional_de_accion_contra_las_violencias_por_motivos_de_genero/programa-acompanar',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-support.jpg',
      imageAlt: 'Dos personas acompañándose al aire libre',
    },
    {
      id: 'gestion-pba-2023',
      kind: 'informe',
      year: 2023,
      date: '2023-12-15',
      tag: 'PBA',
      source: 'Ministerio de Mujeres y Diversidad',
      title: 'Informe de gestión 2023',
      excerpt:
        'Balance provincial de políticas de género, Ley Micaela bonaerense y trabajo con los 135 municipios.',
      url: 'https://ministeriodelasmujeres.gba.gob.ar/gestor/uploads/Informe%20de%20gesti%C3%B3n%202023.pdf',
      linkLabel: 'Abrir PDF',
      image: '/assets/news/news-community.jpg',
      imageAlt: 'Encuentro comunitario al aire libre',
    },
    {
      id: 'dispositivos-2023',
      kind: 'informe',
      year: 2023,
      date: '2023-11-01',
      tag: 'PBA',
      source: 'Ministerio de Mujeres y Diversidad',
      title: 'Dispositivos territoriales de protección',
      excerpt:
        'Informe 2023 sobre hogares, casas abiertas y equipos municipales de la red provincial contra las violencias.',
      url: 'https://ministeriodelasmujeres.gba.gob.ar/gestor/uploads/Dispositivos%20Territoriales%202023.pdf',
      linkLabel: 'Abrir PDF',
      image: '/assets/news/news-community.jpg',
      imageAlt: 'Encuentro comunitario al aire libre',
    },
    {
      id: 'abordaje-2023',
      kind: 'informe',
      year: 2023,
      date: '2023-10-01',
      tag: 'Género',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Abordaje integral de las violencias',
      excerpt:
        'Manual 2023 con herramientas para la atención, el riesgo y la autonomía de quienes atraviesan violencias por motivos de género.',
      url: 'https://www.argentina.gob.ar/sites/default/files/2023/10/abordaje_integral_de_las_violencias_por_motivos_de_genero_2023.pdf',
      linkLabel: 'Abrir PDF',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'decreto-409-2023',
      kind: 'normativa',
      year: 2023,
      date: '2023-08-10',
      tag: 'Salud',
      source: 'Boletín Oficial',
      title: 'Reglamentación de la Ley 27.696',
      excerpt:
        'El decreto 409/2023 aprueba la cobertura integral en salud para personas víctimas de violencia de género.',
      url: 'https://www.boletinoficial.gob.ar/detalleAviso/primera/291883/20230810',
      linkLabel: 'Leer decreto',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'asamblea-2023',
      kind: 'nota',
      year: 2023,
      date: '2023-12-07',
      tag: 'Nación',
      source: 'INADI',
      title: 'Asamblea Nacional de Mujeres y LBTTNB',
      excerpt:
        'Se presentó el documento de la 1° Asamblea, con aportes de organizaciones de todo el país.',
      url: 'https://www.argentina.gob.ar/noticias/se-presento-el-documento-de-la-1deg-asamblea-nacional-de-mujeres-y-lbttnb',
      linkLabel: 'Leer nota',
      image: '/assets/news/news-equality.jpg',
      imageAlt: 'Personas caminando juntas por la ciudad',
    },
    {
      id: 'sicvg-2023',
      kind: 'informe',
      year: 2023,
      date: '2023-02-15',
      tag: 'SICVG',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Informe estadístico SICVG 2023',
      excerpt:
        'Segundo informe del Sistema Integrado de Casos de Violencia por Motivos de Género, con datos nacionales de denuncias y atención.',
      url: 'https://www.argentina.gob.ar/sites/default/files/2023/02/2023-segundo-informe-estadistico-sicvg.pdf',
      linkLabel: 'Abrir PDF',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'sicvg-recurso',
      kind: 'recurso',
      year: 2023,
      date: '2023-02-10',
      tag: 'SICVG',
      source: 'Ministerio de Justicia',
      title: 'Informes estadísticos del SICVG',
      excerpt:
        'Repositorio oficial de informes nacionales sobre casos de violencia por motivos de género.',
      url: 'https://www.argentina.gob.ar/generos/informes-estadisticos-nacionales-del-sicvg',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'pna-2022',
      kind: 'programa',
      year: 2022,
      date: '2022-07-01',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Plan Nacional de Acción 2022-2024',
      excerpt:
        'Hoja de ruta federal para prevenir, asistir y reparar violencias por motivos de género, con acciones de distintos organismos.',
      url: 'https://www.argentina.gob.ar/generos/plan-nacional-de-accion-contra-las-violencias-por-motivos-de-genero-2022-2024',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-support.jpg',
      imageAlt: 'Dos personas acompañándose al aire libre',
    },
    {
      id: 'inadi-2022',
      kind: 'informe',
      year: 2022,
      date: '2022-12-01',
      tag: 'INADI',
      source: 'INADI',
      title: 'Memoria anual de gestión 2022',
      excerpt:
        'Última memoria publicada por el organismo: trabajo territorial, asesoramientos y campañas contra la discriminación.',
      url: 'https://www.argentina.gob.ar/noticias/memoria-anual-de-gestion-2022',
      linkLabel: 'Ver y descargar',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'inadi-2021',
      kind: 'informe',
      year: 2021,
      date: '2022-02-01',
      tag: 'INADI',
      source: 'INADI',
      title: 'Memoria anual de gestión 2021',
      excerpt:
        'Informe de gestión con el detalle de denuncias, atención a víctimas y acciones de prevención.',
      url: 'https://www.argentina.gob.ar/sites/default/files/2022/02/memoria_anual_del_inadi_11-1-2022_revisado_edit.pdf',
      linkLabel: 'Abrir PDF',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'memoria-2021-nota',
      kind: 'nota',
      year: 2021,
      date: '2022-02-10',
      tag: 'INADI',
      source: 'INADI',
      title: 'Presentación de la memoria 2021',
      excerpt:
        'Nota oficial sobre la memoria anual: línea de atención, denuncias y expansión territorial del organismo.',
      url: 'https://www.argentina.gob.ar/noticias/memoria-anual-de-gestion-2021',
      linkLabel: 'Leer nota',
      image: '/assets/news/news-equality.jpg',
      imageAlt: 'Personas caminando juntas por la ciudad',
    },
    {
      id: 'plan-discriminacion',
      kind: 'nota',
      year: 2021,
      date: '2021-09-10',
      tag: 'Discriminación',
      source: 'INADI',
      title: 'Foros para un Plan Nacional contra la Discriminación',
      excerpt:
        'Encuentros federales con organizaciones de Cuyo y Patagonia para construir compromisos estatales de igualdad.',
      url: 'https://www.argentina.gob.ar/noticias/plan-nacional-contra-la-discriminacion-siguen-los-encuentros-federales',
      linkLabel: 'Leer nota',
      image: '/assets/news/news-community.jpg',
      imageAlt: 'Encuentro comunitario al aire libre',
    },
    {
      id: 'pna-2020-2022',
      kind: 'programa',
      year: 2021,
      date: '2021-06-01',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Plan Nacional de Acción 2020-2022',
      excerpt:
        'Primera edición del plan federal de abordaje integral de las violencias por motivos de género.',
      url: 'https://www.argentina.gob.ar/generos/plan_nacional_de_accion_contra_las_violencias_por_motivos_de_genero',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-support.jpg',
      imageAlt: 'Dos personas acompañándose al aire libre',
    },
    {
      id: 'pna-resultados',
      kind: 'informe',
      year: 2022,
      date: '2022-06-15',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Resultados del Plan Nacional 2020-2022',
      excerpt:
        'Balance de las medidas implementadas en los dos primeros años del plan federal contra las violencias por motivos de género.',
      url: 'https://www.argentina.gob.ar/noticias/el-mmgyd-presento-los-resultados-del-plan-nacional-de-accion-contra-las-violencias-por',
      linkLabel: 'Leer nota',
      image: '/assets/news/news-equality.jpg',
      imageAlt: 'Personas caminando juntas por la ciudad',
    },
    {
      id: 'comunidades',
      kind: 'programa',
      year: 2020,
      date: '2020-08-01',
      tag: 'PBA',
      source: 'Ministerio de Mujeres y Diversidad',
      title: 'Comunidades sin Violencias',
      excerpt:
        'Programa bonaerense para fortalecer equipos municipales, hogares de protección y acceso al trabajo.',
      url: 'https://ministeriodelasmujeres.gba.gob.ar/pdf/comunidades-sin-violencia.pdf',
      linkLabel: 'Abrir PDF',
      image: '/assets/news/news-community.jpg',
      imageAlt: 'Encuentro comunitario al aire libre',
    },
    {
      id: 'ley-micaela',
      kind: 'normativa',
      year: 2019,
      date: '2019-01-10',
      tag: 'Ley',
      source: 'InfoLEG',
      title: 'Ley Micaela 27.499',
      excerpt:
        'Capacitación obligatoria en género y violencia contra las mujeres para quienes se desempeñan en la función pública.',
      url: 'https://www.argentina.gob.ar/normativa/nacional/ley-27499-318666',
      linkLabel: 'Leer norma',
      image: '/assets/news/news-equality.jpg',
      imageAlt: 'Personas caminando juntas por la ciudad',
    },
    {
      id: 'ley-26485',
      kind: 'normativa',
      year: 2009,
      date: '2009-04-01',
      tag: 'Ley',
      source: 'InfoLEG',
      title: 'Ley 26.485 de protección integral',
      excerpt:
        'Norma nacional de protección contra las violencias hacia las mujeres. Define tipos y modalidades, y obliga al Estado a dar respuesta.',
      url: 'https://servicios.infoleg.gob.ar/infolegInternet/anexos/150000-154999/152155/texact.htm',
      linkLabel: 'Leer norma',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'ley-26485-ficha',
      kind: 'normativa',
      year: 2009,
      date: '2009-04-14',
      tag: 'Ley',
      source: 'InfoLEG',
      title: 'Ficha oficial de la Ley 26.485',
      excerpt:
        'Resumen y texto de la ley de protección integral para prevenir, sancionar y erradicar las violencias.',
      url: 'https://www.argentina.gob.ar/normativa/nacional/ley-26485-152155',
      linkLabel: 'Ver ficha',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'ley-26485-infoleg',
      kind: 'normativa',
      year: 2009,
      date: '2009-04-14',
      tag: 'Ley',
      source: 'InfoLEG',
      title: 'Publicación de la Ley 26.485',
      excerpt:
        'Ficha legislativa: sancionada el 11 de marzo de 2009, promulgada el 1 de abril y publicada el 14 de abril.',
      url: 'https://servicios.infoleg.gob.ar/infolegInternet/verNorma.do?id=152155',
      linkLabel: 'Ver ficha',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'decreto-1011',
      kind: 'normativa',
      year: 2010,
      date: '2010-07-20',
      tag: 'Decreto',
      source: 'InfoLEG',
      title: 'Decreto 1011/2010',
      excerpt:
        'Reglamentación de la Ley 26.485: cómo el Estado debe prevenir, asistir y no revictimizar.',
      url: 'https://servicios.infoleg.gob.ar/infolegInternet/anexos/165000-169999/169478/norma.htm',
      linkLabel: 'Leer decreto',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'ley-trata',
      kind: 'normativa',
      year: 2008,
      date: '2008-04-30',
      tag: 'Trata',
      source: 'InfoLEG',
      title: 'Ley 26.364 de trata de personas',
      excerpt:
        'Prevención y sanción de la trata, y asistencia a las víctimas. Base normativa de la línea 145.',
      url: 'https://servicios.infoleg.gob.ar/infolegInternet/anexos/140000-144999/140100/texact.htm',
      linkLabel: 'Leer norma',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'csjn-ovd-2026',
      kind: 'nota',
      year: 2026,
      date: '2026-04-29',
      tag: 'Justicia',
      source: 'Corte Suprema de Justicia',
      title: 'La Corte difundió el informe anual de la OVD',
      excerpt:
        'Nota de abril de 2026 sobre las 18.014 atenciones de 2025 y el tablero interactivo de la Oficina de Violencia Doméstica.',
      url: 'https://www.csjn.gov.ar/novedades/detalle/13202',
      linkLabel: 'Leer nota',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'linea-145-2026',
      kind: 'recurso',
      year: 2026,
      date: '2026-03-01',
      tag: 'Trata',
      source: 'Ministerio de Justicia',
      title: 'Línea 145 contra la trata',
      excerpt:
        'Canal gratuito y anónimo para denunciar trata y explotación. Funciona las 24 horas, todos los días.',
      url: 'https://www.argentina.gob.ar/denuncia-el-delito-de-trata-de-personas-linea-145',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-helpline.jpg',
      imageAlt: 'Persona sosteniendo un teléfono para pedir ayuda',
    },
    {
      id: 'pba-mujeres-2026',
      kind: 'programa',
      year: 2026,
      date: '2026-02-26',
      tag: 'PBA',
      source: 'Ministerio de Mujeres y Diversidad',
      title: 'Políticas bonaerenses contra las violencias',
      excerpt:
        'Área provincial de igualdad, Línea 144 y programas territoriales de salida de las violencias.',
      url: 'https://www.gba.gob.ar/mujeres',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-community.jpg',
      imageAlt: 'Encuentro comunitario al aire libre',
    },
    {
      id: 'pba-fortalecimiento',
      kind: 'programa',
      year: 2026,
      date: '2026-02-26',
      tag: 'PBA',
      source: 'Ministerio de Mujeres y Diversidad',
      title: 'Programa de Fortalecimiento para la Salida',
      excerpt:
        'Acompañamiento bonaerense y asistencia económica por hasta seis meses, instrumentado en 2026.',
      url: 'https://normas.gba.gob.ar/documentos/B1KONQH4.html',
      linkLabel: 'Ver decreto',
      image: '/assets/news/news-support.jpg',
      imageAlt: 'Dos personas acompañándose al aire libre',
    },
    {
      id: 'pba-productivas-2026',
      kind: 'programa',
      year: 2026,
      date: '2026-08-15',
      tag: 'PBA',
      source: 'Ministerio de Mujeres y Diversidad',
      title: 'Organizadas y en Red 2026',
      excerpt:
        'II convocatoria provincial para fortalecer proyectos productivos de mujeres y LGBTIQ+ organizadas en red.',
      url: 'https://boletinoficial.gba.gob.ar/secciones/14316/ver',
      linkLabel: 'Leer convocatoria',
      image: '/assets/news/news-community.jpg',
      imageAlt: 'Encuentro comunitario al aire libre',
    },
    {
      id: 'res-5350-2026',
      kind: 'normativa',
      year: 2026,
      date: '2026-06-27',
      tag: 'PBA',
      source: 'Boletín Oficial PBA',
      title: 'Resolución 5350-MSALGP-2026',
      excerpt:
        'Aprueba la guía de orientación para equipos interdisciplinarios del Ministerio de Salud bonaerense ante violencias de género.',
      url: 'https://boletinoficial.gba.gob.ar/secciones/14267/ver',
      linkLabel: 'Leer resolución',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'res-productivas-2026',
      kind: 'normativa',
      year: 2026,
      date: '2026-08-01',
      tag: 'PBA',
      source: 'Boletín Oficial PBA',
      title: 'Prórroga de la convocatoria productiva 2026',
      excerpt:
        'Extiende hasta el 15 de agosto de 2026 la inscripción a proyectos productivos de mujeres y LGBTIQ+.',
      url: 'https://boletinoficial.gba.gob.ar/secciones/14316/ver',
      linkLabel: 'Leer resolución',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'rnfja-2025-nota',
      kind: 'normativa',
      year: 2026,
      date: '2026-06-01',
      tag: 'Justicia',
      source: 'Corte Suprema de Justicia',
      title: 'Datos abiertos del Registro de Femicidios',
      excerpt:
        'La Oficina de la Mujer publica las bases 2024-2025 del RNFJA, con el recaudo de la Ley 27.275 de acceso a la información.',
      url: 'https://www.csjn.gov.ar/omrecopilacion/omfemicidio/registroFemicidiosDatosAbiertos.html',
      linkLabel: 'Ver datos abiertos',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'res-401-2025',
      kind: 'normativa',
      year: 2025,
      date: '2025-06-01',
      tag: 'Nación',
      source: 'Ministerio de Justicia',
      title: 'Resolución 401/2025 del Programa Acompañar',
      excerpt:
        'Convoca a quienes pidieron Acompañar entre 2020 y 2023 y no recibieron la prestación, para ratificar el trámite.',
      url: 'https://www.argentina.gob.ar/normativa/nacional/resoluci%C3%B3n-401-2025-414414',
      linkLabel: 'Leer resolución',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'decreto-2640-2025',
      kind: 'normativa',
      year: 2025,
      date: '2025-12-01',
      tag: 'PBA',
      source: 'Gobierno de la Provincia de Buenos Aires',
      title: 'Decreto 2640/2025',
      excerpt:
        'Crea el Programa de Fortalecimiento para la Salida de las Violencias de Género, con asistencia económica de hasta seis meses.',
      url: 'https://normas.gba.gob.ar/documentos/B1KONQH4.html',
      linkLabel: 'Leer decreto',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'violencia-digital-2025',
      kind: 'normativa',
      year: 2025,
      date: '2025-07-08',
      tag: 'Ley',
      source: 'Boletín Oficial',
      title: 'Violencia digital en la Ley 26.485',
      excerpt:
        'Reforma que incorpora la violencia digital o telemática y medidas de no contacto por redes o mensajería.',
      url: 'https://www.boletinoficial.gob.ar/pdf/aviso/primera/296572/20250708',
      linkLabel: 'Leer norma',
      image: '/assets/news/news-equality.jpg',
      imageAlt: 'Personas caminando juntas por la ciudad',
    },
    {
      id: 'ovd-informe-2024',
      kind: 'informe',
      year: 2025,
      date: '2025-05-20',
      tag: 'OVD',
      source: 'Oficina de Violencia Doméstica',
      title: 'Informe estadístico 2024 de la OVD',
      excerpt:
        'En 2024 se atendió a 17.120 personas: 9.840 presentaciones y cerca de 34.000 medidas preventivas judiciales.',
      url: 'https://www.ovd.gov.ar/ovd/novedades/detalle/9922',
      linkLabel: 'Leer informe',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'revifag-2025',
      kind: 'informe',
      year: 2025,
      date: '2025-03-08',
      tag: 'PBA',
      source: 'Ministerio Público de la Provincia',
      title: 'Informe REVIFAG y femicidios 2025',
      excerpt:
        'El Ministerio Público bonaerense relevó 146.046 procesos penales de violencia familiar y de género en 2025.',
      url: 'https://mpba.gov.ar/files/informes/Informe%20REVIFAG%20y%20Femicidios%202025.pdf',
      linkLabel: 'Abrir PDF',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'rnfja-2025',
      kind: 'informe',
      year: 2025,
      date: '2025-12-31',
      tag: 'Justicia',
      source: 'Oficina de la Mujer - CSJN',
      title: 'Registro Nacional de Femicidios 2025',
      excerpt:
        'El RNFJA identificó 204 causas y 200 víctimas directas en 2025, un 12,3% menos que el año anterior.',
      url: 'https://om.csjn.gob.ar/consultaTalleresWeb/public/documentoConsulta/verDocumentoById?idDocumento=384',
      linkLabel: 'Abrir informe',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'csjn-femicidios-2025',
      kind: 'nota',
      year: 2025,
      date: '2025-12-31',
      tag: 'Justicia',
      source: 'Corte Suprema de Justicia',
      title: 'En 2025 disminuyó la cantidad de femicidios',
      excerpt:
        'La Corte informó 200 víctimas directas en 2025. Desde 2017 el descenso acumulado es del 20,6%.',
      url: 'https://www.csjn.gov.ar/novedades/detalle/13522',
      linkLabel: 'Leer nota',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'csjn-ovd-2024-nota',
      kind: 'nota',
      year: 2025,
      date: '2025-05-20',
      tag: 'OVD',
      source: 'Corte Suprema de Justicia',
      title: 'Más de 13.000 personas afectadas en 2024',
      excerpt:
        'La Corte resumió el informe anual de la OVD: 17.120 atenciones y más de 2.000 amenazas de muerte relatadas.',
      url: 'https://www.csjn.gov.ar/novedades/detalle/9903',
      linkLabel: 'Leer nota',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'brechas-pba-2025',
      kind: 'nota',
      year: 2025,
      date: '2025-06-01',
      tag: 'PBA',
      source: 'Gobierno de la Provincia de Buenos Aires',
      title: 'Brechas de género laborales en la Provincia',
      excerpt:
        'Informes trimestrales 2025 sobre empleo, informalidad e ingresos de mujeres en los aglomerados bonaerenses.',
      url: 'https://www.gba.gob.ar/economia/unidad_de_genero_y_economia/informes/brechas_de_g%C3%A9nero_laborales_y_de_ingresos',
      linkLabel: 'Ver informes',
      image: '/assets/news/news-equality.jpg',
      imageAlt: 'Personas caminando juntas por la ciudad',
    },
    {
      id: 'pba-productivas-2025',
      kind: 'programa',
      year: 2025,
      date: '2025-09-28',
      tag: 'PBA',
      source: 'Ministerio de Mujeres y Diversidad',
      title: 'Organizadas y en Red 2025',
      excerpt:
        'I convocatoria bonaerense para fortalecer proyectos productivos de mujeres y LGBTIQ+ en organizaciones comunitarias.',
      url: 'https://boletinoficial.gba.gob.ar/secciones/13732/ver',
      linkLabel: 'Leer convocatoria',
      image: '/assets/news/news-community.jpg',
      imageAlt: 'Encuentro comunitario al aire libre',
    },
    {
      id: 'linea-144-app-2025',
      kind: 'programa',
      year: 2025,
      date: '2025-03-01',
      tag: 'Nación',
      source: 'Ministerio de Justicia',
      title: 'App de la Línea 144',
      excerpt:
        'Aplicación oficial para pedir atención, con videollamada para personas sordas o hipoacúsicas.',
      url: 'https://www.argentina.gob.ar/aplicaciones/linea-144-atencion-mujeres',
      linkLabel: 'Ver aplicación',
      image: '/assets/news/news-helpline.jpg',
      imageAlt: 'Persona sosteniendo un teléfono para pedir ayuda',
    },
    {
      id: 'sicvg-estadisticas-2024',
      kind: 'recurso',
      year: 2024,
      date: '2024-03-01',
      tag: 'SICVG',
      source: 'Ministerio de Justicia',
      title: 'Estadísticas del SICVG',
      excerpt:
        'Informes nacionales, tablero por provincia y municipio, y datos de Acompañar, PAD y Línea 144.',
      url: 'https://www.argentina.gob.ar/generos/estadisticas-del-sicvg',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'sicvg-tableros-2024',
      kind: 'recurso',
      year: 2024,
      date: '2024-03-15',
      tag: 'SICVG',
      source: 'Ministerio de Justicia',
      title: 'Tableros públicos de programas',
      excerpt:
        'Tableros de datos abiertos del Programa Acompañar, la Línea 144 y Acercar Derechos.',
      url: 'https://www.argentina.gob.ar/generos/tableros-de-datos-publicos-de-programas-sicvg',
      linkLabel: 'Ver tableros',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'datos-144-recurso-2024',
      kind: 'recurso',
      year: 2024,
      date: '2024-01-20',
      tag: 'Nación',
      source: 'Datos Argentina',
      title: 'Base de datos de la Línea 144',
      excerpt:
        'Dataset público de comunicaciones de la Línea 144, para consulta o reutilización.',
      url: 'https://www.datos.gob.ar/dataset/generos-base-datos-linea-144',
      linkLabel: 'Ver datos abiertos',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'pna-2022-2024-nota',
      kind: 'nota',
      year: 2024,
      date: '2024-01-10',
      tag: 'Nación',
      source: 'Ministerio de Justicia',
      title: 'Cierre del Plan Nacional 2022-2024',
      excerpt:
        'El plan federal sumó 100 acciones de 20 ministerios para prevenir, asistir y reparar violencias por motivos de género.',
      url: 'https://www.argentina.gob.ar/generos/plan-nacional-de-accion-contra-las-violencias-por-motivos-de-genero-2022-2024',
      linkLabel: 'Ver plan',
      image: '/assets/news/news-equality.jpg',
      imageAlt: 'Personas caminando juntas por la ciudad',
    },
    {
      id: 'ovd-datos-2023',
      kind: 'nota',
      year: 2024,
      date: '2024-05-28',
      tag: 'OVD',
      source: 'Oficina de Violencia Doméstica',
      title: 'Datos abiertos 2023 de la OVD',
      excerpt:
        'La base 2023 suma violencia digital, derivaciones a menores y federal, y pertenencia a fuerzas de seguridad.',
      url: 'https://www.ovd.gov.ar/ovd/novedades/detalle/8305',
      linkLabel: 'Leer nota',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'rnfja-abiertos-2024',
      kind: 'informe',
      year: 2024,
      date: '2024-12-31',
      tag: 'Justicia',
      source: 'Oficina de la Mujer - CSJN',
      title: 'Datos abiertos de femicidios 2024',
      excerpt:
        'Bases de causas, víctimas y sujetos activos del RNFJA 2024, con libro de códigos para su lectura.',
      url: 'https://datos.csjn.gov.ar/group/133158d5-949b-426e-a26f-881438c4c900?groups=om',
      linkLabel: 'Ver datos',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'brechas-pba-2024',
      kind: 'informe',
      year: 2024,
      date: '2024-12-15',
      tag: 'PBA',
      source: 'Gobierno de la Provincia de Buenos Aires',
      title: 'Brechas de género laborales 2024',
      excerpt:
        'Serie trimestral bonaerense sobre empleo, informalidad y brecha de ingresos entre varones y mujeres.',
      url: 'https://www.gba.gob.ar/economia/unidad_de_genero_y_economia/informes/brechas_de_g%C3%A9nero_laborales_y_de_ingresos',
      linkLabel: 'Ver informes',
      image: '/assets/news/news-equality.jpg',
      imageAlt: 'Personas caminando juntas por la ciudad',
    },
    {
      id: 'sicvg-2022-pdf',
      kind: 'informe',
      year: 2024,
      date: '2024-02-01',
      tag: 'SICVG',
      source: 'Ministerio de Justicia',
      title: 'Informe estadístico SICVG 2022',
      excerpt:
        'Informe global con cerca de 700.000 registros de consultas y denuncias de violencias por motivos de género.',
      url: 'https://www.argentina.gob.ar/sites/default/files/2023/02/informe_estadistico_sicvg_2022_.pdf',
      linkLabel: 'Abrir PDF',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'pna-2022-descarga',
      kind: 'programa',
      year: 2024,
      date: '2024-06-01',
      tag: 'Nación',
      source: 'Ministerio de Justicia',
      title: 'Plan Nacional 2022-2024 vigente',
      excerpt:
        'Hoja de ruta federal con Acompañar, Producir y fortalecimiento de la institucionalidad de género en provincias y municipios.',
      url: 'https://www.argentina.gob.ar/generos/plan-nacional-de-accion-contra-las-violencias-por-motivos-de-genero-2022-2024',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-support.jpg',
      imageAlt: 'Dos personas acompañándose al aire libre',
    },
    {
      id: 'faq-acompanar-2024',
      kind: 'programa',
      year: 2024,
      date: '2024-08-25',
      tag: 'Nación',
      source: 'Ministerio de Justicia',
      title: 'Preguntas frecuentes de Acompañar',
      excerpt:
        'Requisitos, compatibilidades y canales de consulta del apoyo económico para personas en riesgo por violencia de género.',
      url: 'https://www.argentina.gob.ar/generos/preguntas-frecuentes-acompanar',
      linkLabel: 'Ver preguntas',
      image: '/assets/news/news-helpline.jpg',
      imageAlt: 'Persona sosteniendo un teléfono para pedir ayuda',
    },
    {
      id: 'pna-2023-nota',
      kind: 'nota',
      year: 2023,
      date: '2023-07-01',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Más Estado, menos violencias',
      excerpt:
        'El PNA 2022-2024 buscó consolidar Acompañar, ampliar el abordaje de la violencia digital y fortalecer equipos interdisciplinarios.',
      url: 'https://www.argentina.gob.ar/noticias/mas-estado-menos-violencias-plan-nacional-de-accion-contra-las-violencias-por-motivos-de',
      linkLabel: 'Leer nota',
      image: '/assets/news/news-equality.jpg',
      imageAlt: 'Personas caminando juntas por la ciudad',
    },
    {
      id: 'pna-chaco-2023',
      kind: 'nota',
      year: 2023,
      date: '2023-05-01',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Presentación del Plan Nacional en Chaco',
      excerpt:
        'Gómez Alcorta presentó el PNA 2022-2024 junto a la Encuesta de Prevalencia de Violencia contra las Mujeres.',
      url: 'https://www.argentina.gob.ar/noticias/en-chaco-gomez-alcorta-presento-el-plan-nacional-de-accion-contra-las-violencias-por',
      linkLabel: 'Leer nota',
      image: '/assets/news/news-community.jpg',
      imageAlt: 'Encuentro comunitario al aire libre',
    },
    {
      id: 'linea-144-2023',
      kind: 'informe',
      year: 2023,
      date: '2023-07-01',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Datos públicos de la Línea 144 (2023)',
      excerpt:
        'Informe de comunicaciones de enero a junio de 2023, con detalle por tipo de violencia y vínculo con el agresor.',
      url: 'https://www.argentina.gob.ar/generos/linea-144/informacion-estadistica',
      linkLabel: 'Ver estadísticas',
      image: '/assets/news/news-helpline.jpg',
      imageAlt: 'Persona sosteniendo un teléfono para pedir ayuda',
    },
    {
      id: 'ley-27696-ficha',
      kind: 'normativa',
      year: 2023,
      date: '2023-08-10',
      tag: 'Salud',
      source: 'InfoLEG',
      title: 'Ficha de la Ley 27.696',
      excerpt:
        'La ley incorpora al PMO un protocolo de abordaje integral para personas víctimas de violencia de género.',
      url: 'https://www.argentina.gob.ar/normativa/nacional/ley-27696-374556',
      linkLabel: 'Ver ficha',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'decreto-1190-2023',
      kind: 'normativa',
      year: 2023,
      date: '2023-06-01',
      tag: 'PBA',
      source: 'Gobierno de la Provincia de Buenos Aires',
      title: 'Decreto 1190/2023',
      excerpt:
        'Reformula el Programa de Abordaje Integral ante Femicidios, Travesticidios y Transfemicidios (PAIF).',
      url: 'https://normas.gba.gob.ar/documentos/0YaQWrid.html',
      linkLabel: 'Leer decreto',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'pna-2022-programa-2023',
      kind: 'programa',
      year: 2023,
      date: '2023-01-15',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Implementación del Plan 2022-2024',
      excerpt:
        'Segundo plan federal: 100 acciones de ministerios y organismos para el abordaje integral de las violencias.',
      url: 'https://www.argentina.gob.ar/generos/plan-nacional-de-accion-contra-las-violencias-por-motivos-de-genero-2022-2024',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-support.jpg',
      imageAlt: 'Dos personas acompañándose al aire libre',
    },
    {
      id: 'producir-2023',
      kind: 'programa',
      year: 2023,
      date: '2023-04-01',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Programa Producir',
      excerpt:
        'Financiamiento a organizaciones comunitarias para proyectos productivos de mujeres y LGBTI+ que atravesaron violencias.',
      url: 'https://www.argentina.gob.ar/generos/plan_nacional_de_accion_contra_las_violencias_por_motivos_de_genero/programa-producir',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-community.jpg',
      imageAlt: 'Encuentro comunitario al aire libre',
    },
    {
      id: 'acercar-derechos-2023',
      kind: 'programa',
      year: 2023,
      date: '2023-04-15',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Programa Acercar Derechos',
      excerpt:
        'Acompañamiento territorial para el acceso a la justicia de mujeres y LGBTI+ en situación de violencias.',
      url: 'https://www.argentina.gob.ar/generos/plan_nacional_de_accion_contra_las_violencias_por_motivos_de_genero/programa-acercar-derechos',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-support.jpg',
      imageAlt: 'Dos personas acompañándose al aire libre',
    },
    {
      id: 'sicvg-recurso-2023b',
      kind: 'recurso',
      year: 2023,
      date: '2023-03-01',
      tag: 'SICVG',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Qué es el SICVG',
      excerpt:
        'Sistema nacional para registrar consultas y denuncias, medir riesgo y articular organismos de todo el país.',
      url: 'https://www.argentina.gob.ar/generos/sistema-integrado-de-casos-de-violencia-por-motivos-de-genero-sicvg',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'om-csjn-2023',
      kind: 'recurso',
      year: 2023,
      date: '2023-06-01',
      tag: 'Justicia',
      source: 'Oficina de la Mujer - CSJN',
      title: 'Oficina de la Mujer de la Corte',
      excerpt:
        'El RNFJA reúne causas, víctimas y sujetos activos de femicidio con información de todas las jurisdicciones.',
      url: 'https://www.csjn.gov.ar/omrecopilacion/omfemicidio/homefemicidio.html',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'sicvg-global-nota',
      kind: 'nota',
      year: 2022,
      date: '2022-12-15',
      tag: 'SICVG',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Primer informe estadístico global del SICVG',
      excerpt:
        'Se presentaron datos 2013-2022: cerca de 700.000 registros de personas asistidas y consultas en todo el país.',
      url: 'https://www.argentina.gob.ar/noticias/el-mmgyd-presento-el-primer-informe-estadistico-global-del-sistema-integrado-de-casos-de',
      linkLabel: 'Leer nota',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'pna-chaco-2022',
      kind: 'nota',
      year: 2022,
      date: '2022-07-15',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Lanzamiento del Plan 2022-2024',
      excerpt:
        'El segundo plan federal se presentó con eje en institucionalidad de género, Acompañar y Producir.',
      url: 'https://www.argentina.gob.ar/noticias/en-chaco-gomez-alcorta-presento-el-plan-nacional-de-accion-contra-las-violencias-por',
      linkLabel: 'Leer nota',
      image: '/assets/news/news-community.jpg',
      imageAlt: 'Encuentro comunitario al aire libre',
    },
    {
      id: 'inadi-2022-nota',
      kind: 'nota',
      year: 2022,
      date: '2022-12-10',
      tag: 'INADI',
      source: 'INADI',
      title: 'Se publicó la memoria de gestión 2022',
      excerpt:
        'Última memoria anual del organismo, con el detalle de asesoramientos, campañas y trabajo territorial.',
      url: 'https://www.argentina.gob.ar/noticias/memoria-anual-de-gestion-2022',
      linkLabel: 'Leer nota',
      image: '/assets/news/news-equality.jpg',
      imageAlt: 'Personas caminando juntas por la ciudad',
    },
    {
      id: 'linea-144-2022',
      kind: 'informe',
      year: 2022,
      date: '2022-12-20',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Datos públicos de la Línea 144 (2022)',
      excerpt:
        'En 2022 se recibieron 125.235 comunicaciones en las tres sedes, 11.896 más que el año anterior.',
      url: 'https://www.argentina.gob.ar/generos/linea-144/datos-publicos-de-la-linea-144-2022',
      linkLabel: 'Ver informe',
      image: '/assets/news/news-helpline.jpg',
      imageAlt: 'Persona sosteniendo un teléfono para pedir ayuda',
    },
    {
      id: 'protex-145-2022',
      kind: 'informe',
      year: 2022,
      date: '2022-12-31',
      tag: 'Trata',
      source: 'PROTEX - Ministerio Público Fiscal',
      title: 'Denuncias de la Línea 145 en 2022',
      excerpt:
        'PROTEX registró 1.581 denuncias de trata y delitos conexos canalizadas por la línea 145.',
      url: 'https://www.mpf.gob.ar/protex/files/2023/11/Protex-informe_Denuncias-Linea-145_2023-2.pdf',
      linkLabel: 'Abrir PDF',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'ley-27696',
      kind: 'normativa',
      year: 2022,
      date: '2022-11-10',
      tag: 'Ley',
      source: 'InfoLEG',
      title: 'Ley 27.696 de abordaje integral en salud',
      excerpt:
        'Incorpora al PMO la cobertura total de prácticas preventivas y terapéuticas para personas víctimas de violencia de género.',
      url: 'https://www.argentina.gob.ar/normativa/nacional/ley-27696-374556/texto',
      linkLabel: 'Leer ley',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'res-55-2022',
      kind: 'normativa',
      year: 2022,
      date: '2022-02-23',
      tag: 'Nación',
      source: 'InfoLEG',
      title: 'Resolución 55/2022',
      excerpt:
        'Creó el Programa Acercar Derechos para personas en situación de violencias por motivos de género.',
      url: 'https://www.argentina.gob.ar/normativa/nacional/resoluci%C3%B3n-55-2022-361233',
      linkLabel: 'Leer resolución',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'ley-27696-resumen',
      kind: 'normativa',
      year: 2022,
      date: '2022-11-10',
      tag: 'Ley',
      source: 'InfoLEG',
      title: 'Resumen de la Ley 27.696',
      excerpt:
        'Ficha oficial: sanción el 27 de octubre de 2022 y publicación el 10 de noviembre.',
      url: 'https://www.argentina.gob.ar/normativa/nacional/ley-27696-374556',
      linkLabel: 'Ver ficha',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'acercar-derechos-2022',
      kind: 'programa',
      year: 2022,
      date: '2022-02-23',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Lanzamiento de Acercar Derechos',
      excerpt:
        'Política de cercanía para abordar de modo integral los derechos vulnerados de quienes atraviesan violencias.',
      url: 'https://www.argentina.gob.ar/generos/plan_nacional_de_accion_contra_las_violencias_por_motivos_de_genero/programa-acercar-derechos',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-support.jpg',
      imageAlt: 'Dos personas acompañándose al aire libre',
    },
    {
      id: 'producir-2022',
      kind: 'programa',
      year: 2022,
      date: '2022-04-01',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Programa Producir en el PNA',
      excerpt:
        'Línea de proyectos productivos del Plan Nacional 2022-2024, con subsidios a organizaciones comunitarias.',
      url: 'https://www.argentina.gob.ar/generos/plan_nacional_de_accion_contra_las_violencias_por_motivos_de_genero/programa-producir',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-community.jpg',
      imageAlt: 'Encuentro comunitario al aire libre',
    },
    {
      id: 'sicvg-2022-recurso',
      kind: 'recurso',
      year: 2022,
      date: '2022-08-01',
      tag: 'SICVG',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Manuales e instructivos del SICVG',
      excerpt:
        'Tutoriales de carga, medición de riesgo y normativa de adhesión para organismos provinciales y municipales.',
      url: 'https://www.argentina.gob.ar/generos/tutoriales-materiales-manuales-e-instructivos-del-sistema-integrado-de-casos-de-violencia',
      linkLabel: 'Ver materiales',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'linea-144-recurso-2022',
      kind: 'recurso',
      year: 2022,
      date: '2022-01-15',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Estadísticas de la Línea 144',
      excerpt:
        'Repositorio de infografías anuales de la línea de atención, contención y asesoramiento.',
      url: 'https://www.argentina.gob.ar/generos/linea-144/informacion-estadistica',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-helpline.jpg',
      imageAlt: 'Persona sosteniendo un teléfono para pedir ayuda',
    },
    {
      id: 'unidades-acompanar-2022',
      kind: 'recurso',
      year: 2022,
      date: '2022-03-01',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Unidades del Programa Acompañar',
      excerpt:
        'Mapa de unidades provinciales y municipales para iniciar o consultar el trámite de Acompañar.',
      url: 'https://www.argentina.gob.ar/generos/unidades-del-programa-acompanar',
      linkLabel: 'Ver unidades',
      image: '/assets/news/news-community.jpg',
      imageAlt: 'Encuentro comunitario al aire libre',
    },
    {
      id: 'linea-144-2021',
      kind: 'informe',
      year: 2021,
      date: '2021-12-20',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Datos públicos de la Línea 144 (2021)',
      excerpt:
        'Se recibieron 113.340 comunicaciones, 4.309 más que en 2020. El 13% tenía medidas de protección vigentes.',
      url: 'https://www.argentina.gob.ar/generos/linea-144/datos-publicos-de-la-linea-144-enero-diciembre-2021',
      linkLabel: 'Ver informe',
      image: '/assets/news/news-helpline.jpg',
      imageAlt: 'Persona sosteniendo un teléfono para pedir ayuda',
    },
    {
      id: 'sicvg-instructivos-2021',
      kind: 'informe',
      year: 2021,
      date: '2021-09-01',
      tag: 'SICVG',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Documentos técnicos del SICVG 2021',
      excerpt:
        'Descripción del módulo de recursos y de la medición automática de riesgo, actualizados en septiembre de 2021.',
      url: 'https://www.argentina.gob.ar/generos/tutoriales-materiales-manuales-e-instructivos-del-sistema-integrado-de-casos-de-violencia',
      linkLabel: 'Ver documentos',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'res-48-2021',
      kind: 'normativa',
      year: 2021,
      date: '2021-02-13',
      tag: 'Nación',
      source: 'Boletín Oficial',
      title: 'Resolución 48/2021',
      excerpt:
        'Crea el SICVG para sistematizar consultas y denuncias de violencias por motivos de género en todo el país.',
      url: 'https://www.argentina.gob.ar/normativa/nacional/resoluci%C3%B3n-48-2021-347091/texto',
      linkLabel: 'Leer resolución',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'res-60-2021',
      kind: 'normativa',
      year: 2021,
      date: '2021-03-01',
      tag: 'Nación',
      source: 'Boletín Oficial',
      title: 'Resolución 60/2021',
      excerpt:
        'Aprueba las actas de adhesión al SICVG para provincias, CABA, municipios y organismos nacionales.',
      url: 'https://www.boletinoficial.gob.ar/detalleAviso/primera/241305/20210301',
      linkLabel: 'Leer resolución',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'res-186-2021',
      kind: 'normativa',
      year: 2021,
      date: '2021-04-26',
      tag: 'Nación',
      source: 'InfoLEG',
      title: 'Resolución 186/2021',
      excerpt:
        'Creó el Programa Producir para fortalecer proyectos productivos de mujeres y LGBTI+ que atravesaron violencias.',
      url: 'https://www.argentina.gob.ar/normativa/nacional/resoluci%C3%B3n-186-2021-349188',
      linkLabel: 'Leer resolución',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'producir-2021',
      kind: 'programa',
      year: 2021,
      date: '2021-04-26',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Lanzamiento del Programa Producir',
      excerpt:
        'Subsidios a organizaciones con o sin personería jurídica para proyectos productivos con perspectiva de género.',
      url: 'https://www.argentina.gob.ar/generos/plan_nacional_de_accion_contra_las_violencias_por_motivos_de_genero/programa-producir',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-community.jpg',
      imageAlt: 'Encuentro comunitario al aire libre',
    },
    {
      id: 'acompanar-2021',
      kind: 'programa',
      year: 2021,
      date: '2021-03-01',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Programa Acompañar en 2021',
      excerpt:
        'Prestación equivalente a un salario mínimo durante seis meses, con acompañamiento psicosocial en todo el país.',
      url: 'https://www.argentina.gob.ar/generos/plan_nacional_de_accion_contra_las_violencias_por_motivos_de_genero/programa-acompanar',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-support.jpg',
      imageAlt: 'Dos personas acompañándose al aire libre',
    },
    {
      id: 'sicvg-recurso-2021',
      kind: 'recurso',
      year: 2021,
      date: '2021-02-13',
      tag: 'SICVG',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Puesta en marcha del SICVG',
      excerpt:
        'Herramienta web para un padrón integrado de casos, con medición de riesgo y articulación entre jurisdicciones.',
      url: 'https://www.argentina.gob.ar/generos/sistema-integrado-de-casos-de-violencia-por-motivos-de-genero-sicvg',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'linea-144-2021-recurso',
      kind: 'recurso',
      year: 2021,
      date: '2021-01-15',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Línea 144: canales 2021',
      excerpt:
        'Atención 24 horas por teléfono, WhatsApp y mail, con infografías públicas del año.',
      url: 'https://www.argentina.gob.ar/linea-144',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-helpline.jpg',
      imageAlt: 'Persona sosteniendo un teléfono para pedir ayuda',
    },
    {
      id: 'faq-acompanar-2021',
      kind: 'recurso',
      year: 2021,
      date: '2021-05-01',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Guía de Acompañar',
      excerpt:
        'Preguntas frecuentes sobre edad, denuncia, compatibilidades y unidades de ingreso al programa.',
      url: 'https://www.argentina.gob.ar/generos/preguntas-frecuentes-acompanar',
      linkLabel: 'Ver guía',
      image: '/assets/news/news-helpline.jpg',
      imageAlt: 'Persona sosteniendo un teléfono para pedir ayuda',
    },
    {
      id: 'nota-pna-2021',
      kind: 'nota',
      year: 2021,
      date: '2021-06-15',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'El Plan Nacional 2020-2022 en marcha',
      excerpt:
        'Primera edición del plan federal: foros participativos, Acompañar y cambio de paradigma en el abordaje de las violencias.',
      url: 'https://www.argentina.gob.ar/generos/plan_nacional_de_accion_contra_las_violencias_por_motivos_de_genero',
      linkLabel: 'Ver plan',
      image: '/assets/news/news-equality.jpg',
      imageAlt: 'Personas caminando juntas por la ciudad',
    },
    {
      id: 'decreto-734-2020',
      kind: 'normativa',
      year: 2020,
      date: '2020-09-09',
      tag: 'Nación',
      source: 'Boletín Oficial',
      title: 'Decreto 734/2020',
      excerpt:
        'Crea el Programa Acompañar: prestación de un salario mínimo durante seis meses para personas en riesgo acreditado.',
      url: 'https://www.boletinoficial.gob.ar/detalleAviso/primera/234705/20200909',
      linkLabel: 'Leer decreto',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'decreto-734-ficha',
      kind: 'normativa',
      year: 2020,
      date: '2020-09-09',
      tag: 'Nación',
      source: 'InfoLEG',
      title: 'Ficha del decreto 734/2020',
      excerpt:
        'Resumen oficial de la creación del Programa de Apoyo y Acompañamiento a personas en situación de riesgo.',
      url: 'https://www.argentina.gob.ar/normativa/nacional/decreto-734-2020-341971',
      linkLabel: 'Ver ficha',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'res-80-2020',
      kind: 'normativa',
      year: 2020,
      date: '2020-07-06',
      tag: 'Nación',
      source: 'InfoLEG',
      title: 'Resolución 80/2020',
      excerpt:
        'Crea el Programa para el Apoyo Urgente y la Asistencia Integral Inmediata ante femicidio, travesticidio y transfemicidio.',
      url: 'https://www.argentina.gob.ar/normativa/nacional/resoluci%C3%B3n-80-2020-339643/texto',
      linkLabel: 'Leer resolución',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'pna-2020-nota',
      kind: 'nota',
      year: 2020,
      date: '2020-07-01',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Presentación del Plan Nacional 2020-2022',
      excerpt:
        'El presidente y la ministra Gómez Alcorta presentaron el primer plan federal contra las violencias por motivos de género.',
      url: 'https://www.argentina.gob.ar/noticias/presentamos-junto-al-presidente-alberto-fernandez-el-plan-nacional-de-accion-contra-las',
      linkLabel: 'Leer nota',
      image: '/assets/news/news-equality.jpg',
      imageAlt: 'Personas caminando juntas por la ciudad',
    },
    {
      id: 'linea-144-2020-nota',
      kind: 'nota',
      year: 2020,
      date: '2020-12-15',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'La Línea 144 en el aislamiento',
      excerpt:
        'Con el ASPO se sumaron mail y WhatsApp. Desde abril de 2020 las comunicaciones superaron todos los meses a 2019.',
      url: 'https://www.argentina.gob.ar/generos/linea-144/datos-publicos-de-la-linea-144-ano-2020',
      linkLabel: 'Leer nota',
      image: '/assets/news/news-helpline.jpg',
      imageAlt: 'Persona sosteniendo un teléfono para pedir ayuda',
    },
    {
      id: 'pna-2020-plan',
      kind: 'nota',
      year: 2020,
      date: '2020-06-15',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Plan Nacional de Acción 2020-2022',
      excerpt:
        'Plan participativo y federal que incorporó la Ley de Identidad de Género al abordaje de las violencias.',
      url: 'https://www.argentina.gob.ar/generos/plan_nacional_de_accion_contra_las_violencias_por_motivos_de_genero',
      linkLabel: 'Ver plan',
      image: '/assets/news/news-support.jpg',
      imageAlt: 'Dos personas acompañándose al aire libre',
    },
    {
      id: 'linea-144-2020',
      kind: 'informe',
      year: 2020,
      date: '2020-12-31',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Datos públicos de la Línea 144 (2020)',
      excerpt:
        '108.403 comunicaciones en el año. En abril, ya en aislamiento, hubo un 23% más que en abril de 2019.',
      url: 'https://www.argentina.gob.ar/generos/linea-144/datos-publicos-de-la-linea-144-ano-2020',
      linkLabel: 'Ver informe',
      image: '/assets/news/news-helpline.jpg',
      imageAlt: 'Persona sosteniendo un teléfono para pedir ayuda',
    },
    {
      id: 'rnfja-abiertos-2020',
      kind: 'informe',
      year: 2020,
      date: '2020-12-31',
      tag: 'Justicia',
      source: 'Oficina de la Mujer - CSJN',
      title: 'Datos abiertos de femicidios 2020',
      excerpt:
        'Bases públicas del Registro Nacional de Femicidios de la Justicia Argentina correspondientes a 2020.',
      url: 'https://www.csjn.gov.ar/omrecopilacion/omfemicidio/registroFemicidiosDatosAbiertos.html?anioBuscar=2020',
      linkLabel: 'Ver datos',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
    {
      id: 'info-publica-generos',
      kind: 'informe',
      year: 2020,
      date: '2020-11-01',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Acceso a la información pública en géneros',
      excerpt:
        'Respuestas oficiales sobre Línea 144, Acompañar y dónde consultar las bases y tableros estadísticos.',
      url: 'https://www.argentina.gob.ar/generos/respuestas-solicitudes-frecuentes-de-acceso-la-informacion-publica',
      linkLabel: 'Ver recurso',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'acompanar-2020',
      kind: 'programa',
      year: 2020,
      date: '2020-09-09',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Nace el Programa Acompañar',
      excerpt:
        'Apoyo económico y redes de acompañamiento para promover un proyecto de vida autónomo y libre de violencias.',
      url: 'https://www.argentina.gob.ar/generos/plan_nacional_de_accion_contra_las_violencias_por_motivos_de_genero/programa-acompanar',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-support.jpg',
      imageAlt: 'Dos personas acompañándose al aire libre',
    },
    {
      id: 'pna-2020-programa',
      kind: 'programa',
      year: 2020,
      date: '2020-06-01',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Plan Nacional de Acción 2020-2022',
      excerpt:
        'Primera hoja de ruta del Ministerio: prevención, asistencia, protección y acceso a la justicia con enfoque federal.',
      url: 'https://www.argentina.gob.ar/generos/plan_nacional_de_accion_contra_las_violencias_por_motivos_de_genero',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-support.jpg',
      imageAlt: 'Dos personas acompañándose al aire libre',
    },
    {
      id: 'linea-144-2020-recurso',
      kind: 'recurso',
      year: 2020,
      date: '2020-04-01',
      tag: 'Nación',
      source: 'Ministerio de las Mujeres, Géneros y Diversidad',
      title: 'Línea 144 en pandemia',
      excerpt:
        'Durante el ASPO la línea sumó WhatsApp y mail para sostener la atención remota las 24 horas.',
      url: 'https://www.argentina.gob.ar/linea-144',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-helpline.jpg',
      imageAlt: 'Persona sosteniendo un teléfono para pedir ayuda',
    },
    {
      id: 'datos-144-2020',
      kind: 'recurso',
      year: 2020,
      date: '2020-12-01',
      tag: 'Nación',
      source: 'Datos Argentina',
      title: 'Base pública de la Línea 144',
      excerpt:
        'Dataset abierto de comunicaciones por violencias de género, publicado para reutilización.',
      url: 'https://www.datos.gob.ar/dataset/generos-base-datos-linea-144',
      linkLabel: 'Ver datos abiertos',
      image: '/assets/news/news-documents.jpg',
      imageAlt: 'Documentos e informes sobre un escritorio',
    },
    {
      id: 'ovd-recurso-2020',
      kind: 'recurso',
      year: 2020,
      date: '2020-03-20',
      tag: 'Justicia',
      source: 'Corte Suprema de Justicia',
      title: 'OVD: atención 24 horas',
      excerpt:
        'La oficina de Lavalle 1250 siguió recibiendo denuncias de violencia doméstica todos los días, sin turno previo.',
      url: 'https://ovd.gob.ar/ovd/',
      linkLabel: 'Ver sitio oficial',
      image: '/assets/news/news-justice.jpg',
      imageAlt: 'Fachada de un edificio de justicia al atardecer',
    },
  ];

  get olderCount(): number {
    return this.news.filter((item) => item.year < 2020).length;
  }

  get filteredNews(): NewsItem[] {
    return this.news
      .filter((item) => this.selectedKind === 'todas' || item.kind === this.selectedKind)
      .filter((item) => {
        if (this.selectedYear === 'todos') {
          return true;
        }
        if (this.selectedYear === 'anteriores') {
          return item.year < 2020;
        }
        return item.year === this.selectedYear;
      })
      .sort((a, b) => b.date.localeCompare(a.date));
  }

  get featuredNews(): NewsItem[] {
    const filtered = this.filteredNews;
    const featured = filtered.filter((item) => item.featured);
    return (featured.length ? featured : filtered).slice(0, 6);
  }

  get libraryNews(): NewsItem[] {
    const featuredIds = new Set(this.featuredNews.map((item) => item.id));
    return this.filteredNews.filter((item) => !featuredIds.has(item.id));
  }

  setKind(kind: 'todas' | NewsKind): void {
    this.selectedKind = kind;
    this.resetCarousel();
  }

  setYear(year: number | 'todos' | 'anteriores'): void {
    this.selectedYear = year;
    this.resetCarousel();
  }

  scrollCarousel(direction: number): void {
    const scroller = this.carousel()?.nativeElement;
    if (!scroller) {
      return;
    }

    const card = scroller.querySelector('.story-card');
    const amount = card instanceof HTMLElement ? card.offsetWidth + 16 : 320;
    scroller.scrollBy({ left: direction * amount, behavior: 'smooth' });
  }

  private resetCarousel(): void {
    this.carousel()?.nativeElement.scrollTo({ left: 0, behavior: 'smooth' });
  }
}
